name = "telegram-uploader-bot"
main = "src/index.js"
compatibility_date = "2024-06-11"

# Cloudflare KV Binding
[[kv_namespaces]]
binding = "TETGRAM-DB_KV"
id = "e4f716a3ac1148459c22658e76b90be5" # آیدی KV شما (بر اساس اِکانت آیدی لاگ شما حدس زده شده، اگر اشتباست از پنل چک کنید)

# Cloudflare D1 Binding
[[d1_databases]]
binding = "DB_D1"
database_name = "telegram-uploader-bot"
database_id = "449bd1d8-4e08-4abc-972b-586a2d349880" # آیدی دیتابیس D1 شما از لاگ بیلد قبلی

# Environment Variables (Production)
[vars]
BOT_TOKEN = "8828889841:AAH6Z5Xj8yJTIwZWULqYhf7k_mYuXYIp71o"
BOT_USERNAME = "NasimMovie_Bot"
MAIN_CHANNEL_ID = "-1004223334690"
DATABASE_CHANNEL_ID = "-1004208092671"
ADMIN_CACHE_TTL = "3600"